MYUSERNAME="BHARATH"
MYPASSWORD="HHHH"
echo MYUSERNAME = $MYUSERNAME
echo MYPASSWORD = $MYPASSWORD 
STARTOFSCRIPT="Wednesday 06 April 2022 10:55:16 PM IST"
ENDOFSCRIPT="Wednesday 06 April 2022 10:55:16 PM IST"
echo STARTOFSCRIPT = $STARTOFSCRIPT
echo ENDOFSCRIPT = $ENDOFSCRIPT
